import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import { networksTable, devicesTable, insertNetworkSchema } from "@workspace/db/schema";
import { eq, count } from "drizzle-orm";

const router: IRouter = Router();

router.get("/", async (req, res) => {
  try {
    const networks = await db.select().from(networksTable);
    const withCount = await Promise.all(
      networks.map(async (n) => {
        const [{ value }] = await db.select({ value: count() }).from(devicesTable).where(eq(devicesTable.networkId, n.id));
        return { ...n, deviceCount: Number(value) };
      })
    );
    res.json(withCount);
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to list networks" });
  }
});

router.post("/", async (req, res) => {
  try {
    const parsed = insertNetworkSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.message });
    const [network] = await db.insert(networksTable).values(parsed.data).returning();
    res.status(201).json({ ...network, deviceCount: 0 });
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to create network" });
  }
});

router.get("/:id", async (req, res) => {
  try {
    const [network] = await db.select().from(networksTable).where(eq(networksTable.id, Number(req.params.id)));
    if (!network) return res.status(404).json({ error: "Network not found" });
    const [{ value }] = await db.select({ value: count() }).from(devicesTable).where(eq(devicesTable.networkId, network.id));
    res.json({ ...network, deviceCount: Number(value) });
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to get network" });
  }
});

router.delete("/:id", async (req, res) => {
  try {
    const networkId = Number(req.params.id);
    // Nullify the network reference on any devices belonging to this network
    // before deleting to avoid FK constraint violations
    await db.update(devicesTable).set({ networkId: null }).where(eq(devicesTable.networkId, networkId));
    await db.delete(networksTable).where(eq(networksTable.id, networkId));
    res.status(204).send();
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to delete network" });
  }
});

router.post("/:id/generate-ovpn", async (req, res) => {
  try {
    const [network] = await db.select().from(networksTable).where(eq(networksTable.id, Number(req.params.id)));
    if (!network) return res.status(404).json({ error: "Network not found" });

    const { deviceId, commonName } = req.body;
    const now = new Date();

    const ovpnConfig = `# Oh-My-Guard! Generated OVPN Configuration
# Network: ${network.name}
# Device: ${commonName}
# Generated: ${now.toISOString()}
client
dev tun
proto ${network.protocol}
remote vpn.Oh-My-Guard!.internal ${network.port}
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-GCM
auth SHA256
tls-version-min 1.3
verb 3

<ca>
# CA Certificate (generated by Oh-My-Guard! CA)
-----BEGIN CERTIFICATE-----
MIIBxTCCAW+gAwIBAgIJAKSampleAegisCA...
-----END CERTIFICATE-----
</ca>

<cert>
# Client Certificate for ${commonName}
-----BEGIN CERTIFICATE-----
MIIBxTCCAW+gAwIBAgIJAKSampleClient...
-----END CERTIFICATE-----
</cert>

<key>
# Client Private Key for ${commonName}
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSk...
-----END PRIVATE KEY-----
</key>

<tls-auth>
# TLS Auth Key
-----BEGIN OpenVPN Static key V1-----
sample_tls_auth_key_placeholder
-----END OpenVPN Static key V1-----
</tls-auth>
`;

    res.json({
      deviceId,
      networkId: network.id,
      commonName,
      config: ovpnConfig,
      generatedAt: now.toISOString(),
    });
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to generate OVPN config" });
  }
});

export default router;
