---
apiVersion: v1
kind: Namespace
metadata:
  name: securewatch-integration
  labels:
    app.kubernetes.io/part-of: securewatch
---
apiVersion: v1
kind: Namespace
metadata:
  name: securewatch-core
  labels:
    app.kubernetes.io/part-of: securewatch
---
apiVersion: v1
kind: Namespace
metadata:
  name: securewatch-data
  labels:
    app.kubernetes.io/part-of: securewatch
---
apiVersion: v1
kind: Namespace
metadata:
  name: securewatch-frontend
  labels:
    app.kubernetes.io/part-of: securewatch
---
apiVersion: v1
kind: Namespace
metadata:
  name: securewatch-monitoring
  labels:
    app.kubernetes.io/part-of: securewatch
